version: "3.9"

services:
  db:
    image: postgres:13.6
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./output/postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    build: .
    container_name: task_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://task_user:task_pass@db:5432/task_db
      TEST_DATABASE_URL: postgresql+psycopg2://task_user:task_pass@db:5432/task_test_db
