version: "3.9"

services:
  db:
    image: postgres:13.6
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./output/postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    profiles: ["prod"]

  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task_backend_dev
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    profiles: ["dev"]
